/* E-Report SAGS · V1.37 A/C LIMITS / AIRCRAFT RESTRICTIONS
   Admin: manual entry + quick paste only. No image/AI import.
   Runtime: match active flight/A-C REG; general limits alert at STA-10, ASU-related limits alert at ETD-10 (fallback STD-10).
*/
(()=>{
'use strict';
const ACL_VERSION='1.4.1';
const ACL_DOC='AC_LIMITS_CATALOG_V1';
const ACL_HISTORY_PREFIX='AC_LIMITS_HISTORY_';
const ACL_KIND='sags_ac_limits_catalog_v1';
const ACL_SIGNAL='ac_limits/catalog_signal';
const ACL_PUBLIC='ac_limits/catalog_public';
const ACL_CACHE='sags_ac_limits_catalog_cache_v1';
const ACL_ACK='sags_ac_limits_ack_v1';
const ACL_DEFAULT_ROLES=['DH','CBTT','VHTTB','PVHK','PVHLNG'];
const ACL_CATEGORIES=['APU INOP','HOLD INOP/ISSUES','SEAT INOP','OTHERS'];
let aclCatalog={version:0,items:[],dailyDate:'',dailyVersion:''};
let aclSignalRef=null,aclSignalCb=null,aclPollTimer=null;
let aclCurrentAlert=null,aclAlertQueue=[];
let aclEditingManualId='';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').trim().toUpperCase();
const normFlight=v=>norm(v).replace(/[^A-Z0-9]/g,'');
const normReg=v=>norm(v).replace(/[^A-Z0-9]/g,'');
const uid=()=>`ACL_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`.toUpperCase();
const clone=v=>JSON.parse(JSON.stringify(v??null));
function aclDb(){if(typeof initHandoverFirebase!=='function')throw new Error('Firebase chưa sẵn sàng.');return initHandoverFirebase();}
function aclActor(){try{return currentActor?.()||{role:String(currentRole||''),username:String(currentUserProfile?.username||'')}}catch(_){return {role:''}}}
function aclNormRole(v){let s=String(v||'').trim().toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');s=s.replace(/Đ/g,'D').replace(/[^A-Z0-9]/g,'');if(s==='DH'||s==='DIEUHANH')return 'DH';if(s==='LNF'||s==='LOSTANDFOUND'||s==='LOSTFOUND')return 'LOSTFOUND';return s}
function aclRole(){try{return aclNormRole(currentRole||currentUserProfile?.role||currentUserProfile?.roleCode||'')}catch(_){return ''}}
function aclIsAdmin(){return aclRole()==='AD'}
function todayISO(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function aclRolesFromHost(host){return [...host.querySelectorAll('input[type=checkbox][data-acl-role]:checked')].map(x=>aclNormRole(x.dataset.aclRole||'')).filter(Boolean)}
function aclRolesHtml(prefix,selected=ACL_DEFAULT_ROLES){const set=new Set((selected||[]).map(x=>String(x).toUpperCase()));const roles=['DH','CBTT','PVHK','VHTTB','KTTB','PVHLNG','LOSTFOUND','AD'];return `<div class="aclRoleGrid">${roles.map(r=>`<label><input type="checkbox" data-acl-role="${r}" id="${prefix}_${r}" ${set.has(r)?'checked':''}> ${r}</label>`).join('')}</div>`}
function aclNormalizeItem(x={}){return {
 id:String(x.id||uid()),source:String(x.source||'MANUAL').toUpperCase(),active:x.active!==false,
 airline:norm(x.airline||''),flightNo:normFlight(x.flightNo||''),acReg:normReg(x.acReg||''),displayReg:norm(x.displayReg||x.acReg||''),
 matchMode:String(x.matchMode||((x.flightNo&&x.acReg)?'BOTH':x.flightNo?'FLIGHT':'REG')).toUpperCase(),
 category:ACL_CATEGORIES.includes(norm(x.category))?norm(x.category):'OTHERS',restriction:String(x.restriction||'').trim(),
 effectiveFrom:String(x.effectiveFrom||''),effectiveTo:String(x.effectiveTo||''),batchDate:String(x.batchDate||''),batchVersion:String(x.batchVersion||''),
 recipientRoles:[...new Set((x.recipientRoles||ACL_DEFAULT_ROLES).map(aclNormRole).filter(Boolean))],
 createdAtMs:Number(x.createdAtMs||Date.now()),updatedAtMs:Number(x.updatedAtMs||Date.now()),createdBy:x.createdBy||null,updatedBy:x.updatedBy||null
}}
function aclSaveCache(){try{localStorage.setItem(ACL_CACHE,JSON.stringify({at:Date.now(),catalog:aclCatalog}))}catch(_){}}
function aclLoadCache(){try{const x=JSON.parse(localStorage.getItem(ACL_CACHE)||'null');if(x?.catalog){aclCatalog={version:Number(x.catalog.version||0),items:(x.catalog.items||[]).map(aclNormalizeItem),dailyDate:String(x.catalog.dailyDate||''),dailyVersion:String(x.catalog.dailyVersion||'')};return true}}catch(_){}return false}
function aclSetStatus(text,err=false){const e=$('aclAdminStatus');if(e){e.textContent=text||'';e.style.color=err?'#b42318':'#40566b'}}
function aclInjectCss(){if($('aclStyle'))return;const s=document.createElement('style');s.id='aclStyle';s.textContent=`
#aclAdminModal,#aclAlertModal{position:fixed;inset:0;z-index:13950;display:none;background:rgba(0,0,0,.6);padding:max(8px,env(safe-area-inset-top)) 7px max(8px,env(safe-area-inset-bottom));box-sizing:border-box;overflow:auto;align-items:flex-start;justify-content:center}
.aclPanel{width:min(98vw,1050px);max-height:96dvh;overflow:auto;background:#fff;border-radius:16px;padding:14px;box-sizing:border-box;font:13px/1.4 Arial;color:#203040;box-shadow:0 18px 52px rgba(0,0,0,.36)}
.aclTop{position:sticky;top:-14px;z-index:5;background:#fff;display:flex;align-items:center;justify-content:space-between;gap:8px;padding:5px 0 10px;border-bottom:1px solid #dde5ec}.aclTop h3{margin:0;color:#003B8E;font:900 19px Arial}.aclClose{border:0;background:#e9eef3;border-radius:9px;padding:9px 13px;font-weight:900}
.aclTabs{display:flex;gap:6px;overflow:auto;position:sticky;top:43px;background:#fff;z-index:4;padding:8px 0}.aclTab{white-space:nowrap;border:1px solid #bac6d1;background:#f7f9fb;border-radius:9px;padding:8px 10px;font-weight:900}.aclTab.active{background:#003B8E;color:#fff;border-color:#003B8E}.aclPane{display:none}.aclPane.active{display:block}
.aclCard{border:1px solid #d6dfe7;background:#fbfcfe;border-radius:12px;padding:11px;margin:9px 0}.aclTitle{font:900 15px Arial;color:#17324d;margin-bottom:7px}.aclHint{background:#eef6ff;border-left:4px solid #0b67b2;border-radius:9px;padding:9px;margin:8px 0;font-weight:700;color:#274862}.aclWarn{background:#fff0ef;border:2px solid #d92d20;border-radius:10px;padding:10px;color:#9d1c14;font-weight:900}
.aclGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.aclGrid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.aclLabel{display:block;font:900 11px Arial;color:#4c5d6c;margin:4px 0}.aclInput,.aclSelect,.aclText{width:100%;box-sizing:border-box;border:1px solid #aeb9c4;border-radius:8px;padding:9px;background:#fff;font:700 13px Arial}.aclText{min-height:70px;resize:vertical}.aclBtn{border:0;border-radius:8px;min-height:36px;padding:8px 11px;font-weight:900;background:#003B8E;color:#fff}.aclBtn.secondary{background:#e8eef5;color:#234;border:1px solid #c3ced8}.aclBtn.good{background:#167947}.aclBtn.danger{background:#b42318}.aclActions{display:flex;gap:7px;flex-wrap:wrap;margin:9px 0}.aclRoleGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px}.aclRoleGrid label{border:1px solid #d7e0e8;border-radius:8px;padding:7px;background:#fff;font-weight:800}.aclItem{border:1px solid #d8e0e7;border-radius:10px;padding:9px;margin:7px 0;background:#fff}.aclItem b{color:#123b63}.aclMeta{font-size:11px;color:#607080;margin-top:4px}.aclDraftRow{display:grid;grid-template-columns:150px 180px 1fr auto;gap:6px;align-items:start;margin:6px 0}.aclDraftRow input,.aclDraftRow select{width:100%;box-sizing:border-box;border:1px solid #b8c3cc;border-radius:7px;padding:7px;font:700 12px Arial}.aclDraftRow textarea{width:100%;min-height:48px;box-sizing:border-box;border:1px solid #b8c3cc;border-radius:7px;padding:7px;font:700 12px Arial}
#aclAlertModal{z-index:14980;align-items:center;padding:12px}.aclAlertBox{width:min(94vw,520px);background:#fff;border:4px solid #d92d20;border-radius:16px;padding:16px;box-sizing:border-box;box-shadow:0 20px 60px rgba(0,0,0,.45)}.aclAlertTitle{color:#b42318;font:900 21px Arial;margin:0 0 7px}.aclAlertFlight{font:900 17px Arial;color:#172b4d;margin:5px 0}.aclAlertLine{background:#fff0ef;border-left:5px solid #d92d20;border-radius:7px;padding:9px;margin:7px 0;font-weight:900;white-space:pre-wrap}.aclAck{width:100%;border:0;border-radius:10px;padding:12px;background:#b42318;color:#fff;font:900 16px Arial;margin-top:10px}
@media(max-width:650px){.aclGrid,.aclGrid3{grid-template-columns:1fr}.aclRoleGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.aclDraftRow{grid-template-columns:1fr 1fr}.aclDraftRow textarea{grid-column:1/-1}.aclDraftRow .aclDraftDel{grid-column:1/-1}}
`;document.head.appendChild(s)}
function aclEnsureButton(){if($('roleBtnAcLimits'))return;const row=document.querySelector('.toolbar-row.main-actions');if(!row)return;const b=document.createElement('button');b.id='roleBtnAcLimits';b.textContent='A/C LIMITS';b.style.display='none';b.onclick=()=>aclOpenAdmin();const anchor=$('roleBtnAdminBuilder')||$('roleBtnManual');if(anchor)row.insertBefore(b,anchor);else row.appendChild(b)}
function aclRefreshRoleUI(){aclEnsureButton();const b=$('roleBtnAcLimits');if(b)b.style.display=(aclIsAdmin()&&!window.SAGS_ADMIN_HUB_V137)?'inline-flex':'none'}
function aclEnsureUi(){aclInjectCss();aclEnsureButton();if(!$('aclAdminModal')){const d=document.createElement('div');d.id='aclAdminModal';d.innerHTML=`<div class="aclPanel"><div class="aclTop"><h3>A/C LIMITS · AIRCRAFT RESTRICTIONS</h3><button class="aclClose" onclick="aclCloseAdmin()">ĐÓNG</button></div><div class="aclTabs">
<button class="aclTab active" data-acltab="manual" onclick="aclTab('manual')">1 · THÊM CẢNH BÁO</button><button class="aclTab" data-acltab="quick" onclick="aclTab('quick')">2 · DÁN NHANH</button><button class="aclTab" data-acltab="list" onclick="aclTab('list')">3 · ĐANG HIỆU LỰC</button><button class="aclTab" data-acltab="help" onclick="aclTab('help')">HDSD</button></div>
<div id="aclAdminStatus" style="min-height:20px;font-weight:800"></div>
<div id="aclPaneManual" class="aclPane active"></div><div id="aclPaneQuick" class="aclPane"></div><div id="aclPaneList" class="aclPane"></div><div id="aclPaneHelp" class="aclPane"></div></div>`;document.body.appendChild(d)}
if(!$('aclAlertModal')){const a=document.createElement('div');a.id='aclAlertModal';a.innerHTML=`<div class="aclAlertBox"><div class="aclAlertTitle">⚠ A/C LIMITS</div><div id="aclAlertFlight" class="aclAlertFlight"></div><div id="aclAlertBody"></div><button class="aclAck" onclick="aclAckAlert()">ĐÃ BIẾT</button></div>`;document.body.appendChild(a)}
aclRenderAll()}
function aclTab(name){document.querySelectorAll('#aclAdminModal .aclTab').forEach(x=>x.classList.toggle('active',x.dataset.acltab===name));document.querySelectorAll('#aclAdminModal .aclPane').forEach(x=>x.classList.remove('active'));const p=$('aclPane'+name.charAt(0).toUpperCase()+name.slice(1));if(p)p.classList.add('active');if(name==='list')aclRenderList()}
function aclOpenAdmin(){if(!aclIsAdmin())return alert('Chỉ AD được dùng A/C LIMITS.');aclEnsureUi();$('aclAdminModal').style.display='flex';aclLoadCatalog(true).then(()=>aclRenderAll()).catch(e=>aclSetStatus(String(e?.message||e),true))}
function aclCloseAdmin(){const m=$('aclAdminModal');if(m)m.style.display='none'}
function aclRenderAll(){aclRenderManualPane();aclRenderQuickPane();aclRenderList();aclRenderHelp()}
function aclRenderManualPane(){const h=$('aclPaneManual');if(!h)return;h.innerHTML=`<div class="aclCard"><div class="aclTitle">THÊM CẢNH BÁO A/C LIMITS</div><div class="aclHint">Nhập trực tiếp Flight No / A/C Reg và nội dung cần cảnh báo. Dùng được cho mọi hãng. Ví dụ <b>BX782 · HL7269 · NEED GPU ASU</b>.</div><div class="aclGrid3">
<div><label class="aclLabel">Hãng</label><input id="aclManAirline" class="aclInput" placeholder="BX"></div><div><label class="aclLabel">Flight No</label><input id="aclManFlight" class="aclInput" placeholder="BX782"></div><div><label class="aclLabel">A/C Reg</label><input id="aclManReg" class="aclInput" placeholder="HL7269"></div>
<div><label class="aclLabel">Khớp theo</label><select id="aclManMode" class="aclSelect"><option value="BOTH">FLIGHT + REG</option><option value="REG">A/C REG</option><option value="FLIGHT">FLIGHT NO</option></select></div><div><label class="aclLabel">Nhóm</label><select id="aclManCat" class="aclSelect">${ACL_CATEGORIES.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div><label class="aclLabel">Từ ngày</label><input id="aclManFrom" class="aclInput" type="date" value="${todayISO()}"></div><div><label class="aclLabel">Đến ngày</label><input id="aclManTo" class="aclInput" type="date" value="${todayISO()}"></div></div><label class="aclLabel">Nội dung hạn chế</label><textarea id="aclManText" class="aclText" placeholder="NEED GPU ASU"></textarea><label class="aclLabel">Đối tượng nhận</label>${aclRolesHtml('aclManRole',ACL_DEFAULT_ROLES)}<div class="aclActions"><button class="aclBtn good" onclick="aclSaveManual()">${aclEditingManualId?'LƯU THAY ĐỔI':'LƯU & ÁP DỤNG'}</button><button class="aclBtn secondary" onclick="aclClearManual()">XÓA Ô</button></div></div>`}
function aclClearManual(){aclEditingManualId='';['aclManAirline','aclManFlight','aclManReg','aclManText'].forEach(id=>{if($(id))$(id).value=''});if($('aclManFrom'))$('aclManFrom').value=todayISO();if($('aclManTo'))$('aclManTo').value=todayISO()}
async function aclSaveManual(){if(!aclIsAdmin())return;const flight=normFlight($('aclManFlight')?.value),reg=normReg($('aclManReg')?.value),mode=String($('aclManMode')?.value||'BOTH'),text=String($('aclManText')?.value||'').trim(),roles=aclRolesFromHost($('aclPaneManual'));if(!text)return alert('Nhập nội dung hạn chế.');if(mode==='BOTH'&&(!flight||!reg))return alert('Khớp FLIGHT + REG cần nhập đủ Flight No và A/C Reg.');if(mode==='REG'&&!reg)return alert('Cần nhập A/C Reg.');if(mode==='FLIGHT'&&!flight)return alert('Cần nhập Flight No.');if(!roles.length)return alert('Chọn ít nhất 1 đối tượng nhận.');const stamp=Date.now(),oldItem=aclEditingManualId?(aclCatalog.items||[]).find(x=>x.id===aclEditingManualId):null,item=aclNormalizeItem({id:oldItem?.id||uid(),source:oldItem?.source||'MANUAL',airline:$('aclManAirline')?.value,flightNo:flight,acReg:reg,displayReg:$('aclManReg')?.value,matchMode:mode,category:$('aclManCat')?.value,restriction:text,effectiveFrom:$('aclManFrom')?.value,effectiveTo:$('aclManTo')?.value,recipientRoles:roles,createdAtMs:oldItem?.createdAtMs||stamp,createdBy:oldItem?.createdBy||aclActor(),updatedAtMs:stamp,updatedBy:aclActor()});try{const arr=oldItem?(aclCatalog.items||[]).map(x=>x.id===oldItem.id?item:x):[...(aclCatalog.items||[]),item];await aclWriteCatalog(arr,{action:oldItem?'MANUAL_EDIT':'MANUAL_ADD'});aclSetStatus(`${oldItem?'Đã sửa':'Đã thêm'} ${flight||''} ${item.displayReg||reg} · ${text}`);aclEditingManualId='';aclRenderManualPane();aclRenderList()}catch(e){aclSetStatus('Không lưu được: '+String(e?.message||e),true)}}
function aclRenderQuickPane(){const h=$('aclPaneQuick');if(!h)return;h.innerHTML=`<div class="aclCard"><div class="aclTitle">DÁN NHANH THÔNG BÁO HÃNG</div><div class="aclHint">Ví dụ: <b>BX782 HL7269 NEED GPU ASU</b>. Hệ thống tách Flight / Reg / nội dung rồi đưa sang mục THÊM TAY để anh kiểm tra trước khi lưu.</div><textarea id="aclQuickText" class="aclText" placeholder="BX782 HL7269 NEED GPU ASU"></textarea><div class="aclActions"><button class="aclBtn" onclick="aclQuickParse()">TÁCH THÔNG TIN</button></div><div id="aclQuickResult"></div></div>`}
function aclQuickParse(){const raw=norm($('aclQuickText')?.value);if(!raw)return;const tokens=raw.split(/\s+/),reg=tokens.find(t=>/^(?:HL\d{4}|VN-?A[A-Z0-9]+|B-?[A-Z0-9]{3,6}|HS-?[A-Z0-9]{3,6}|RP-C\d+|9M-?[A-Z0-9]+)$/.test(t))||'',flight=tokens.find(t=>t!==reg&&/^[A-Z0-9]{2,3}\d{2,5}[A-Z]?$/.test(t))||'';const idxs=[flight?tokens.indexOf(flight):-1,reg?tokens.indexOf(reg):-1].filter(x=>x>=0);const after=idxs.length?Math.max(...idxs)+1:0,text=tokens.slice(after).join(' ').trim();aclTab('manual');$('aclManFlight').value=flight;$('aclManReg').value=reg;$('aclManAirline').value=(flight.match(/^([A-Z0-9]{2,3}?)(?=\d)/)||['',''])[1];$('aclManText').value=text;if(flight&&reg)$('aclManMode').value='BOTH';else if(reg)$('aclManMode').value='REG';else $('aclManMode').value='FLIGHT';if(/APU|GPU|ASU|ACU/.test(text))$('aclManCat').value='APU INOP';aclSetStatus(`Đã tách: ${flight||'(chưa thấy Flight)'} · ${reg||'(chưa thấy Reg)'} · ${text||'(chưa thấy nội dung)'}. Kiểm tra rồi bấm LƯU & ÁP DỤNG.`)}
function aclRuntimeDiagnostic(){const cs=aclContexts(),role=aclRole(),now=Date.now();return cs.map(c=>{const matches=(aclCatalog.items||[]).filter(x=>aclMatch(x,c)&&(x.recipientRoles||[]).map(aclNormRole).includes(role));const general=matches.filter(x=>!aclIsAsuItem(x)),asu=matches.filter(aclIsAsuItem);const g=general[0]?aclTimingForItem(general[0],c):{event:'STA',clock:c.sta,due:c.sta?aclStaMs(c.date,c.sta)-10*60000:null};const a=asu[0]?aclTimingForItem(asu[0],c):{event:c.etd?'ETD':'STD',clock:c.etd||c.std,due:(c.etd||c.std)?(aclDepartureMs(c)-10*60000):null};return {...c,now,matches:matches.length,generalCount:general.length,asuCount:asu.length,generalTiming:g,asuTiming:a}})}
function aclShowDiagnostic(){const rows=aclRuntimeDiagnostic();if(!rows.length)return alert('Máy này chưa có chuyến nào để kiểm tra A/C LIMITS.');const fmt=x=>x?new Date(x).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}):'(không tính được)';alert(rows.map(x=>`${x.flightLabel} · REG ${x.reg||'(trống)'} · ROLE ${aclRole()||'(trống)'}\nSTA ${x.sta||'(trống)'} → LIMIT chung T-10 ${fmt(x.generalTiming?.due)} · MATCH ${x.generalCount}\n${x.asuTiming?.event||'STD'} ${x.asuTiming?.clock||'(trống)'} → ASU T-10 ${fmt(x.asuTiming?.due)} · MATCH ${x.asuCount}`).join('\n\n'))}
function aclRenderList(){const h=$('aclPaneList');if(!h)return;const arr=(aclCatalog.items||[]).slice().sort((a,b)=>Number(b.active)-Number(a.active)||Number(b.updatedAtMs)-Number(a.updatedAtMs));h.innerHTML=`<div class="aclCard"><div class="aclTitle">DANH SÁCH A/C LIMITS</div><div class="aclHint">Toàn bộ cảnh báo được AD nhập thủ công hoặc tạo từ DÁN NHANH. Có thể SỬA / TẮT / BẬT / XÓA từng cảnh báo.</div><div class="aclActions"><button class="aclBtn secondary" onclick="aclLoadCatalog(true).then(aclRenderList)">LÀM MỚI</button><button class="aclBtn secondary" onclick="aclShowDiagnostic()">KIỂM TRA T-10 TRÊN MÁY NÀY</button></div>${arr.length?arr.map(aclItemHtml).join(''):'<div class="aclHint">Chưa có hạn chế.</div>'}</div>`}
function aclItemHtml(x){const key=esc(x.id);const who=(x.recipientRoles||[]).join(', '),srcLabel=String(x.source||'MANUAL').startsWith('IMAGE')?'LEGACY':String(x.source||'MANUAL');return `<div class="aclItem"><b>${esc(x.category)} · ${esc(x.displayReg||x.acReg||'')}</b>${x.flightNo?` · <b>${esc(x.flightNo)}</b>`:''}<div>${esc(x.restriction)}</div><div class="aclMeta">${esc(srcLabel)} · ${esc(x.matchMode)} · ${esc(x.effectiveFrom||'')} → ${esc(x.effectiveTo||'')} · Nhận: ${esc(who)} · ${x.active?'ĐANG BẬT':'ĐÃ TẮT'}</div><div class="aclActions"><button class="aclBtn secondary" onclick="aclToggleItem('${key}',${x.active?'false':'true'})">${x.active?'TẮT':'BẬT'}</button><button class="aclBtn secondary" onclick="aclEditItem('${key}')">SỬA</button><button class="aclBtn danger" onclick="aclDeleteItem('${key}')">XÓA</button></div></div>`}
async function aclToggleItem(id,on){const arr=(aclCatalog.items||[]).map(x=>x.id===id?aclNormalizeItem({...x,active:!!on,updatedAtMs:Date.now(),updatedBy:aclActor()}):x);await aclWriteCatalog(arr,{action:on?'REACTIVATE':'DEACTIVATE'});aclRenderList()}
async function aclDeleteItem(id){if(!confirm('Xóa hạn chế này khỏi danh sách?'))return;await aclWriteCatalog((aclCatalog.items||[]).filter(x=>x.id!==id),{action:'DELETE'});aclRenderList()}
function aclEditItem(id){const x=(aclCatalog.items||[]).find(v=>v.id===id);if(!x)return;aclEditingManualId=id;aclRenderManualPane();aclTab('manual');$('aclManAirline').value=x.airline||'';$('aclManFlight').value=x.flightNo||'';$('aclManReg').value=x.displayReg||x.acReg||'';$('aclManMode').value=x.matchMode||'REG';$('aclManCat').value=x.category||'OTHERS';$('aclManFrom').value=x.effectiveFrom||todayISO();$('aclManTo').value=x.effectiveTo||todayISO();$('aclManText').value=x.restriction||'';document.querySelectorAll('#aclPaneManual input[data-acl-role]').forEach(c=>c.checked=(x.recipientRoles||[]).includes(c.dataset.aclRole));aclSetStatus('Đang sửa hạn chế. Bấm LƯU THAY ĐỔI khi xong.')}
function aclRenderHelp(){const h=$('aclPaneHelp');if(!h)return;h.innerHTML=`<div class="aclCard"><div class="aclTitle">HDSD · A/C LIMITS</div><ol>
<li><b>Thêm cảnh báo:</b> AD → A/C LIMITS → <b>THÊM CẢNH BÁO</b>. Nhập Hãng (nếu cần), Flight No, A/C Reg, nội dung hạn chế/cảnh báo, ngày hiệu lực và đối tượng nhận.</li>
<li><b>Chọn kiểu khớp:</b> REG = cảnh báo theo đăng bạ; FLIGHT = theo số chuyến; FLIGHT + REG = chỉ cảnh báo khi cả hai cùng khớp.</li>
<li><b>Dán nhanh:</b> dùng cho tin nhắn ngắn như <code>BX782 HL7269 NEED GPU ASU</code> → bấm <b>TÁCH THÔNG TIN</b> → hệ thống điền Flight/Reg/nội dung vào form → kiểm tra → <b>LƯU & ÁP DỤNG</b>.</li>
<li><b>Nhiều hạn chế cùng một tàu:</b> nhập thành nhiều cảnh báo riêng. Khi tới mốc, hệ thống gom các hạn chế đang khớp để người làm chuyến thấy đầy đủ.</li>
<li><b>Thời điểm cảnh báo:</b> hạn chế chung cảnh báo từ <b>STA - 10 phút</b>. Riêng nội dung có chữ <b>ASU</b>: ưu tiên <b>ETD - 10 phút</b>; nếu chưa có ETD thì dùng <b>STD - 10 phút</b>. Nếu đã qua mốc mà chưa PUSHBACK, cảnh báo vẫn xuất hiện.</li>
<li><b>Đối tượng nhận:</b> chỉ các Role được AD chọn mới nhận popup. Cùng chuyến + cùng bản hạn chế chỉ cảnh báo một lần sau khi bấm <b>ĐÃ BIẾT</b>; nếu AD sửa nội dung thành bản mới thì có thể cảnh báo lại.</li>
<li><b>Kiểm tra trước khi khai thác:</b> vào <b>ĐANG HIỆU LỰC → KIỂM TRA T-10 TRÊN MÁY NÀY</b> để xem Flight / Reg / Role / mốc thời gian / số LIMIT đang match.</li>
</ol><div class="aclWarn">A/C LIMITS không còn dùng UP ẢNH hoặc AI. Mọi cảnh báo do AD chủ động nhập/chỉnh sửa trực tiếp để dữ liệu gọn và dễ kiểm soát.</div></div>`}
function aclApplyCatalog(d){d=d||{};aclCatalog={version:Number(d.version||0),items:(d.items||[]).map(aclNormalizeItem),dailyDate:String(d.dailyDate||''),dailyVersion:String(d.dailyVersion||'')};aclSaveCache();return aclCatalog}
async function aclWriteCatalog(items,meta={}){if(!aclIsAdmin())throw new Error('Chỉ AD được cập nhật A/C LIMITS.');const now=Date.now(),catalog={kind:ACL_KIND,version:now,dailyDate:meta.dailyDate??aclCatalog.dailyDate??'',dailyVersion:meta.dailyVersion??aclCatalog.dailyVersion??'',items:(items||[]).map(aclNormalizeItem),updatedAtMs:now,updatedBy:aclActor()};const db=aclDb(),old=clone(aclCatalog);await db.collection(HANDOVER_COLLECTION).doc(ACL_DOC).set(catalog,{merge:false});try{await db.collection(HANDOVER_COLLECTION).doc(ACL_HISTORY_PREFIX+now).set({kind:'sags_ac_limits_history_v1',action:String(meta.action||'UPDATE'),oldVersion:Number(old?.version||0),newVersion:now,oldCount:Array.isArray(old?.items)?old.items.length:0,newCount:catalog.items.length,dailyDate:catalog.dailyDate,dailyVersion:catalog.dailyVersion,createdAtMs:now,createdBy:aclActor()},{merge:false})}catch(_){}aclApplyCatalog(catalog);try{if(typeof sagsV470Ref==='function'){await sagsV470Ref(ACL_PUBLIC).set(catalog);await sagsV470Ref(ACL_SIGNAL).set({version:now,action:String(meta.action||'UPDATE'),updatedAtMs:now,updatedBy:aclActor()})}}catch(e){console.info('A/C LIMITS RTDB publish',e?.message||e)}aclEvaluateSoon();return catalog}
async function aclLoadCatalog(force=false){if(!force&&aclCatalog.version)return aclCatalog;let loaded=false;try{if(typeof sagsV470Ref==='function'){const snap=await sagsV470Ref(ACL_PUBLIC).once('value'),d=snap?.val?.();if(d?.version){aclApplyCatalog(d);loaded=true}}}catch(e){console.info('A/C LIMITS RTDB read fallback',e?.message||e)}if(!loaded){try{const s=await aclDb().collection(HANDOVER_COLLECTION).doc(ACL_DOC).get();if(s.exists){const d=s.data()||{};aclApplyCatalog(d);loaded=true;if(aclIsAdmin()&&typeof sagsV470Ref==='function'){try{await sagsV470Ref(ACL_PUBLIC).set({...d,items:(d.items||[]).map(aclNormalizeItem)})}catch(_){}}}}catch(e){if(!aclCatalog.version)aclLoadCache();if(force&&!aclCatalog.version)throw e}}aclEvaluateSoon();return aclCatalog}
function aclStartSignal(){try{if(aclSignalRef||typeof sagsV470Ref!=='function')return;aclSignalRef=sagsV470Ref(ACL_SIGNAL);aclSignalCb=async snap=>{const v=Number(snap?.val?.()?.version||0);if(v&&v!==Number(aclCatalog.version||0)){try{await aclLoadCatalog(true);aclRenderList()}catch(_){}}};aclSignalRef.on('value',aclSignalCb)}catch(e){console.info('A/C LIMITS signal',e?.message||e)}}
function aclIdentityFor(sessionId,st,meta){st=(st&&typeof st==='object')?st:{};meta=meta||null;let identity={};try{identity=fs09IdentityFromState?.(st,meta)||{}}catch(_){try{identity=opsRampIdentity?.(st,meta)||{}}catch(__){identity={}}}const pick=(...keys)=>{for(const k of keys){const v=String(st?.[k]??'').trim();if(v&&v.toUpperCase()!=='N/A')return v}return ''};let flights=Array.isArray(identity.flights)?identity.flights.map(normFlight).filter(Boolean):[];if(!flights.length){flights=[pick('fltBefore','f421_fltBefore','f551_fltBefore','f09_fltBefore'),pick('fltAfter','f421_fltAfter','f551_fltAfter','f09_fltAfter')].map(normFlight).filter(Boolean)}const reg=normReg(identity.acRegToken||identity.regn||pick('regn','f421_regn','f551_regn','f09_regn','acReg','acreg','f421_acReg','f421_acreg','f551_acReg','f09_acReg'));const date=aclIdentityDate(identity,pick('date','f421_date','f551_date','f09_date'));const sta=pick('sta','f421_sta','f551_sta','f09_sta');const std=pick('std','f421_std','f551_std','f09_std');const etd=pick('etd','f421_etd','f551_etd','f09_etd');const pushback=pick('pushback','f421_pushback','f551_pushback','f09_pushback','h24Start','f421_h24Start','f551_h24Start','f09_h24Start');const sid=String(sessionId||'').trim()||`AUTO_${date}_${flights.join('_')}_${reg}`;return {sessionId:sid,flightLabel:flights.join('/')||String(meta?.name||'CHUYẾN'),flights,reg,date,sta,std,etd,pushback}}
function aclIdentity(){let st={},meta=null,sid='';try{sid=String(typeof activeFlightSessionId!=='undefined'?activeFlightSessionId:'');meta=currentFlightSessionMeta?.()||null;const env=readFlightSessionEnvelope?.(sid)||{};st=(typeof state==='object'&&state)||env?.state||{}}catch(_){st={}}return aclIdentityFor(sid,st,meta)}
function aclContexts(){const out=[],seen=new Set();const add=(sid,st,meta)=>{const c=aclIdentityFor(sid,st,meta);const k=c.sessionId;if(!k||seen.has(k))return;seen.add(k);out.push(c)};try{const active=aclIdentity();add(active.sessionId,(typeof state==='object'&&state)||{},currentFlightSessionMeta?.()||null)}catch(_){}try{const list=typeof readFlightSessionList==='function'?readFlightSessionList():[];(list||[]).forEach(meta=>{const sid=String(meta?.id||'');if(!sid||seen.has(sid))return;const env=readFlightSessionEnvelope?.(sid)||{};add(sid,env?.state||{},meta)})}catch(_){}return out}
function aclIdentityDate(identity,raw){let v=String(identity?.dateToken||raw||'').trim();if(/^\d{8}$/.test(v)){if(Number(v.slice(0,4))>1900)return `${v.slice(0,4)}-${v.slice(4,6)}-${v.slice(6,8)}`;return `${v.slice(4,8)}-${v.slice(2,4)}-${v.slice(0,2)}`}return aclDateToISO(v)||todayISO()}
function aclClockMinutes(v){const d=String(v||'').replace(/[^0-9]/g,'');if(d.length<3||d.length>4)return null;const s=d.padStart(4,'0'),h=Number(s.slice(0,2)),m=Number(s.slice(2));return h<=23&&m<=59?h*60+m:null}
function aclClockMs(date,clock){const m=aclClockMinutes(clock);if(m===null)return null;const a=String(date||todayISO()).split('-').map(Number);if(a.length!==3||!a[0]||!a[1]||!a[2])return null;return new Date(a[0],a[1]-1,a[2],Math.floor(m/60),m%60,0,0).getTime()}
function aclStaMs(date,sta){return aclClockMs(date,sta)}
function aclIsAsuItem(item){return /(^|[^A-Z])ASU([^A-Z]|$)/i.test(String(item?.restriction||''))}
function aclDepartureMs(ctx){const clock=ctx.etd||ctx.std;if(!clock)return null;let ms=aclClockMs(ctx.date,clock);if(!ms)return null;const staMs=aclStaMs(ctx.date,ctx.sta);if(staMs&&ms+12*60*60*1000<staMs)ms+=24*60*60*1000;return ms}
function aclTimingForItem(item,ctx){if(aclIsAsuItem(item)){const clock=ctx.etd||ctx.std;const ms=aclDepartureMs(ctx);return {kind:'ASU',event:ctx.etd?'ETD':'STD',clock,ms,due:ms?ms-10*60*1000:null}}const ms=aclStaMs(ctx.date,ctx.sta);return {kind:'GENERAL',event:'STA',clock:ctx.sta,ms,due:ms?ms-10*60*1000:null}}
function aclDateWithin(item,date){const f=item.effectiveFrom||'',t=item.effectiveTo||'';if(f&&date<f)return false;if(t&&date>t)return false;return true}
function aclMatch(item,ctx){if(!item.active||!item.restriction||!aclDateWithin(item,ctx.date))return false;const mode=item.matchMode||'REG',fm=item.flightNo?ctx.flights.includes(normFlight(item.flightNo)):false,rm=item.acReg?normReg(item.acReg)===ctx.reg:false;if(mode==='BOTH')return !!item.flightNo&&!!item.acReg&&fm&&rm;if(mode==='FLIGHT')return !!item.flightNo&&fm;return !!item.acReg&&rm}
function aclAckStore(){try{return JSON.parse(localStorage.getItem(ACL_ACK)||'{}')||{}}catch(_){return {}}}
function aclAckKey(ctx,items){const sig=items.map(x=>`${x.id}:${Number(x.updatedAtMs||0)}:${String(x.restriction||'')}`).sort().join(',');return `${ctx.sessionId}|${ctx.date}|${ctx.flightLabel}|${ctx.reg}|${sig}`}
function aclEvaluateSoon(){setTimeout(()=>{try{aclEvaluate()}catch(_){}},80)}
function aclEvaluate(){if(!aclCatalog.version||!aclRole())return;const role=aclRole(),acks=aclAckStore(),now=Date.now();for(const ctx of aclContexts()){if((!ctx.flights.length&&!ctx.reg)||ctx.pushback)continue;const matches=(aclCatalog.items||[]).filter(x=>aclMatch(x,ctx)&&(x.recipientRoles||[]).map(aclNormRole).includes(role));if(!matches.length)continue;for(const kind of ['GENERAL','ASU']){const items=matches.filter(x=>(aclIsAsuItem(x)?'ASU':'GENERAL')===kind);if(!items.length)continue;const timing=aclTimingForItem(items[0],ctx);if(!timing.due||now<timing.due)continue;const key=aclAckKey(ctx,items)+'|'+kind+'|'+String(timing.event||'');if(Number(acks[key]||0)>0)continue;if(aclCurrentAlert?.key===key||aclAlertQueue.some(x=>x.key===key))continue;aclEnqueueAlert({key,ctx,items,dueAtMs:timing.due,catalogVersion:aclCatalog.version,timing})}}}
function aclEnqueueAlert(a){aclAlertQueue.push(a);aclTryShowNext()}
function aclTryShowNext(){if(aclCurrentAlert||!aclAlertQueue.length)return;try{if(typeof opsVisibleAlerts!=='undefined'&&opsVisibleAlerts.size){setTimeout(aclTryShowNext,1200);return}}catch(_){}aclCurrentAlert=aclAlertQueue.shift();aclShowAlert(aclCurrentAlert)}
function aclShowAlert(a){aclEnsureUi();const f=$('aclAlertFlight'),b=$('aclAlertBody'),t=a.timing||{event:'STA',clock:a.ctx.sta,kind:'GENERAL'};if(f)f.textContent=`${a.ctx.flightLabel}${a.ctx.reg?' · A/C '+a.ctx.reg:''} · ${t.event} ${t.clock||'—'} · ${t.kind==='ASU'?'CẢNH BÁO ASU T-10':'CẢNH BÁO A/C LIMITS T-10'}`;if(b)b.innerHTML=a.items.map(x=>`<div class="aclAlertLine"><b>${esc(x.category)}</b>${x.displayReg||x.acReg?` · ${esc(x.displayReg||x.acReg)}`:''}${x.flightNo?` · ${esc(x.flightNo)}`:''}<br>${esc(x.restriction)}</div>`).join('');$('aclAlertModal').style.display='flex';try{navigator.vibrate?.([450,180,450])}catch(_){}try{writeUserActivity?.(t.kind==='ASU'?'A/C LIMITS · ASU T-10':'A/C LIMITS · STA T-10',`${a.ctx.flightLabel} · ${a.ctx.reg} · ${a.items.length} cảnh báo`,{acLimitCount:a.items.length,sta:a.ctx.sta,std:a.ctx.std,etd:a.ctx.etd,triggerEvent:t.event,triggerClock:t.clock})}catch(_){}}
function aclAckAlert(){if(!aclCurrentAlert)return;const acks=aclAckStore();acks[aclCurrentAlert.key]=Date.now();try{localStorage.setItem(ACL_ACK,JSON.stringify(acks))}catch(_){}$('aclAlertModal').style.display='none';aclCurrentAlert=null;setTimeout(aclTryShowNext,180)}
function aclInit(){aclEnsureUi();aclLoadCache();aclRefreshRoleUI();aclLoadCatalog(false).catch(()=>{});aclStartSignal();if(aclPollTimer)clearInterval(aclPollTimer);aclPollTimer=setInterval(()=>{aclRefreshRoleUI();aclEvaluate()},5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)aclEvaluateSoon()});window.addEventListener('pageshow',aclEvaluateSoon)}
window.aclOpenAdmin=aclOpenAdmin;window.aclCloseAdmin=aclCloseAdmin;window.aclTab=aclTab;window.aclSaveManual=aclSaveManual;window.aclClearManual=aclClearManual;window.aclQuickParse=aclQuickParse;window.aclLoadCatalog=aclLoadCatalog;window.aclRenderList=aclRenderList;window.aclToggleItem=aclToggleItem;window.aclDeleteItem=aclDeleteItem;window.aclEditItem=aclEditItem;window.aclAckAlert=aclAckAlert;window.aclEvaluate=aclEvaluate;window.aclShowDiagnostic=aclShowDiagnostic;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',aclInit,{once:true});else setTimeout(aclInit,0);
})();
