/* E-REPORT SAGS V2.3 · Compact Admin Management Hub */
(function(root){'use strict';
 const S=v=>String(v??'').trim(), U=v=>S(v).toUpperCase();
 function isAD(){try{return U(root.currentRole||root.currentUserProfile?.role)==='AD'}catch(_){return false}}
 const groups=[
  {title:'✈ VẬN HÀNH CHUYẾN',items:[['roleBtnDailyRoster','DAILY ROSTER · TẠO CHUYẾN'],['roleBtnRosterFlights','DANH SÁCH CHUYẾN HÔM NAY'],['roleBtnActivity','TIẾN ĐỘ'],['roleBtnAcLimits','A/C LIMITS'],['roleBtnFleet','FLEET TÀU BAY']]},
  {title:'👥 NHÂN SỰ & CẤU HÌNH',items:[['roleBtnAccounts','TÀI KHOẢN & PHÂN QUYỀN'],['roleBtnAdminBuilder','ADMIN BUILDER']]},
  {title:'🛡 GIÁM SÁT & HỒ SƠ',items:[['roleBtnAudit','NHẬT KÝ / AUDIT'],['roleBtnFirebaseUsage','FIREBASE USAGE'],['roleBtnArchive','HỒ SƠ']]}
 ];
 const hideIds=['roleBtnDailyRoster','roleBtnActivity','roleBtnAcLimits','roleBtnFleet','roleBtnAccounts','roleBtnAdminBuilder','roleBtnAudit','roleBtnFirebaseUsage','roleBtnArchive'];
 function ensure(){if(!document.getElementById('adminHubStyle')){const st=document.createElement('style');st.id='adminHubStyle';st.textContent=`body.sagsAdminHub ${hideIds.map(x=>'#'+x).join(',body.sagsAdminHub ')}{display:none!important}#adminHubModal{display:none;position:fixed;inset:0;z-index:17600;background:rgba(0,0,0,.55);align-items:center;justify-content:center;padding:12px;font-family:Arial,sans-serif}#adminHubModal.show{display:flex}.ahPanel{width:min(95vw,720px);max-height:92vh;overflow:auto;background:#fff;border-radius:16px;padding:14px;box-shadow:0 18px 48px rgba(0,0,0,.35)}.ahHead{display:flex;align-items:center;justify-content:space-between;gap:10px}.ahHead h3{margin:0;color:#0b4f91}.ahClose,.ahItem{border:0;border-radius:10px;font-weight:900;cursor:pointer}.ahClose{padding:8px 11px;background:#eef2f6;color:#334}.ahGroup{margin-top:12px;border:1px solid #dce5ec;border-radius:12px;padding:10px}.ahGroup h4{margin:0 0 8px;color:#294b66}.ahGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.ahItem{min-height:48px;padding:9px 10px;text-align:left;background:#eef6ff;color:#164e7a;border:1px solid #c9def0}.ahItem:hover{background:#e1f0fc}.ahItem.missing{opacity:.45}.ahSub{font-size:12px;color:#667788;margin-top:4px}@media(max-width:560px){.ahGrid{grid-template-columns:1fr}}`;document.head.appendChild(st)}
  if(!document.getElementById('adminHubModal')){const m=document.createElement('div');m.id='adminHubModal';m.innerHTML=`<div class="ahPanel"><div class="ahHead"><div><h3>⚙ QUẢN LÝ ADMIN</h3><div class="ahSub">Các chức năng tương tự được gom theo nhóm. Logic của từng chức năng giữ nguyên.</div></div><button class="ahClose" onclick="adminHubClose()">ĐÓNG</button></div><div id="adminHubBody"></div></div>`;document.body.appendChild(m)}
  const bar=document.querySelector('.toolbar-row.main-actions');if(bar&&!document.getElementById('roleBtnAdminHub')){const b=document.createElement('button');b.id='roleBtnAdminHub';b.textContent='⚙ QUẢN LÝ';b.onclick=()=>root.adminHubOpen();const anchor=document.getElementById('roleBtnAccounts');if(anchor?.parentNode)anchor.parentNode.insertBefore(b,anchor);else bar.appendChild(b)}
 }
 function render(){const host=document.getElementById('adminHubBody');if(!host)return;host.innerHTML=groups.map(g=>`<div class="ahGroup"><h4>${g.title}</h4><div class="ahGrid">${g.items.map(([id,label])=>{const exists=!!document.getElementById(id);return `<button class="ahItem${exists?'':' missing'}" ${exists?`onclick="adminHubRun('${id}')"`:'disabled'}>${label}</button>`}).join('')}</div></div>`).join('')}
 root.adminHubRun=function(id){const b=document.getElementById(id);if(!b)return alert('Chức năng này chưa sẵn sàng.');root.adminHubClose();const old=b.style.display;b.style.setProperty('display','inline-flex','important');try{b.click()}finally{setTimeout(()=>{b.style.display=old||'';sync()},0)}};
 root.adminHubOpen=function(){ensure();render();document.getElementById('adminHubModal')?.classList.add('show')};
 root.adminHubClose=function(){document.getElementById('adminHubModal')?.classList.remove('show')};
 function sync(){ensure();const ad=isAD();document.body.classList.toggle('sagsAdminHub',ad);const b=document.getElementById('roleBtnAdminHub');if(b)b.style.display=ad?'inline-flex':'none'}
 const base=root.applyRoleUI;if(typeof base==='function')root.applyRoleUI=function(){const r=base.apply(this,arguments);setTimeout(sync,0);return r};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(sync,50),{once:true});else setTimeout(sync,50);
 root.__ADMIN_HUB_HDSD='AD chỉ dùng một nút QUẢN LÝ. VẬN HÀNH CHUYẾN: Daily Roster/Tạo chuyến, Danh sách chuyến, Tiến độ, A/C Limits, Fleet. NHÂN SỰ & CẤU HÌNH: Tài khoản/Phân quyền, Admin Builder. GIÁM SÁT & HỒ SƠ: Audit, Firebase Usage, Hồ sơ. CHUYẾN HÔM NAY vẫn giữ ngoài thanh chính cho mọi nhân viên.';
})(typeof window!=='undefined'?window:globalThis);
