/* E-REPORT SAGS V2.3 · MASTER FLIGHT HUB
 * One Daily Roster flight = one master flight record. Operational modules keep their canonical data
 * but register a compact pointer/status under the same flightId so every department works in one flight workspace.
 */
(function(root){'use strict';
  const BUILD='V2.3-20260820-01';
  const ROOT='flight_records', MANIFEST='roster_manifests', MAIL='roster_mail';
  const S=v=>String(v??'').trim(), U=v=>S(v).toUpperCase();
  const safe=v=>S(v).replace(/[.#$\[\]\/]/g,'_');
  const normFlight=v=>U(v).replace(/[^A-Z0-9]/g,'');
  const hash=s=>{let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h.toString(36).toUpperCase()};
  const clone=v=>{try{return JSON.parse(JSON.stringify(v))}catch(_){return v}};
  function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function isoDate(v){const s=S(v);let m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s);if(m)return s;m=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(s);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=/^(\d{8})$/.exec(s.replace(/\D/g,''));if(m){const x=m[1];if(Number(x.slice(0,4))>2000)return `${x.slice(0,4)}-${x.slice(4,6)}-${x.slice(6,8)}`;return `${x.slice(4,8)}-${x.slice(2,4)}-${x.slice(0,2)}`;}return today()}
  function splitFlights(raw){const s=U(raw).replace(/[\/]+/g,' '),out=[];let prefix='';for(const p0 of s.split(/\s+/).filter(Boolean)){const p=p0.replace(/[^A-Z0-9]/g,'');let m=/^([A-Z0-9]{2,3}?)(\d{1,5})$/.exec(p);if(m&&/[A-Z]/.test(m[1])){prefix=m[1];out.push(prefix+m[2]);continue}m=/^(\d{1,5})$/.exec(p);if(m&&prefix)out.push(prefix+m[1]);}return [...new Set(out)]}
  function flightId(date,arr,dep,raw){const flights=[normFlight(arr),normFlight(dep)].filter(Boolean);if(!flights.length)flights.push(...splitFlights(raw).map(normFlight));const sig=`${isoDate(date)}|${flights.join('|')||normFlight(raw)||'UNKNOWN'}`;return `FLT_${hash(sig)}`}
  function extractMailByAssignment(patch){const out={};for(const [k,v] of Object.entries(patch||{})){const m=/^roster_mail\/[^/]+\/items\/([^/]+)$/.exec(k);if(m&&v&&typeof v==='object')out[S(v.assignmentId||m[1])]=v;}return out}
  function enrichRosterPatch(patch){const mails=extractMailByAssignment(patch);for(const [k,v] of Object.entries(patch||{})){const m=/^roster_manifests\/([^/]+)$/.exec(k);if(!m||!v?.items)continue;const date=m[1],records={};for(const [aid,item0] of Object.entries(v.items||{})){const item={...item0},mail=mails[aid]||{};const fid=flightId(date,mail.arrFlight,mail.depFlight,item.flightRaw||mail.flightRaw);item.flightId=fid;v.items[aid]=item;if(mails[aid])mails[aid].flightId=fid;const rec=records[fid]||(records[fid]={flightId:fid,opDate:date,flightRaw:S(item.flightRaw||mail.flightRaw),flightName:S(item.flightName||mail.flightName),arrFlight:S(mail.arrFlight),depFlight:S(mail.depFlight),sta:S(mail.sta),std:S(mail.std),acReg:S(mail.acReg),acType:S(mail.acType),route:S(mail.route),bay:S(mail.bay),createdFrom:'DAILY_ROSTER',createdAtMs:Date.now(),updatedAtMs:Date.now(),assignments:{}});rec.assignments[aid]={assignmentId:aid,user:S(item.user||mail.targetUser),originalUser:S(item.originalUser||mail.originalTargetUser),formGroup:S(item.formGroup||mail.formGroup),sourceColumn:S(item.sourceColumn||mail.sourceColumn),roleKey:S(item.roleKey||mail.roleKey),workspaceKey:S(item.workspaceKey||item.rosterWorkspaceKey||mail.workspaceKey||mail.rosterWorkspaceKey),assignmentScope:S(item.assignmentScope||mail.assignmentScope||'BOTH'),active:item.active!==false};}
      for(const [fid,rec] of Object.entries(records))patch[`${ROOT}/${safe(date)}/${safe(fid)}`]=rec;
      v.flightHubSchema=1;
    }}
  async function readDate(date){try{return (await root.sagsV470Ref(`${ROOT}/${safe(date)}`).once('value')).val()||{}}catch(_){return {}}}
  function identity(payload,meta){const id=payload?.identity||{},f09=payload?.f09||{},st=payload?.state||{};const rawFlights=[];for(const x of [id.flightToken,...(id.flights||[]),payload?.flight,payload?.flightRaw,f09.f09_fltBefore,f09.f09_fltAfter,st.fltBefore,st.fltAfter,st.f421_fltBefore,st.f421_fltAfter])if(S(x))rawFlights.push(normFlight(x));const flights=[...new Set(rawFlights.filter(Boolean))];const date=isoDate(meta?.opDate||id.date||id.dateToken||payload?.date||f09.f09_date||st.date||st.f421_date||meta?.date||today());return {date,flights,reg:S(id.acRegToken||payload?.acReg||payload?.acreg||f09.f09_regn||st.regn||st.f421_regn).toUpperCase()}}
  function matchRecord(records,flights){const fset=new Set(flights);for(const rec of Object.values(records||{})){const rfl=[rec.arrFlight,rec.depFlight,...splitFlights(rec.flightRaw),...splitFlights(rec.flightName)].map(normFlight).filter(Boolean);if(rfl.some(x=>fset.has(x)))return rec;}return null}
  function moduleSummary(kind,payload,meta){const k=U(kind),id=identity(payload,meta);const base={kind:k,updatedAtMs:Date.now(),updatedBy:S(root.currentUserProfile?.username||root.currentRole||''),docId:S(meta?.docId),sourcePath:S(meta?.sourcePath),revisionNo:Number(meta?.revisionNo||payload?.revisionNo||payload?.closeoutNo||0)||0,reg:id.reg};if(k==='KẾT SỔ'||k==='KET_SO'||k==='CLOSEOUT')return {...base,kind:'KẾT SỔ',status:'ĐÃ CÓ',adl:payload?.f09?.f09_finalADL??null,chd:payload?.f09?.f09_finalCHD??null,inf:payload?.f09?.f09_finalINF??null,bagPcs:payload?.f09?.f09_finalBagP??null,bagKg:payload?.f09?.f09_finalBagW??null};if(k==='FINAL')return {...base,status:'ĐÃ CÓ',form:S(payload?.form),crosscheckStatus:S(payload?.cleanCrosscheck?.[String(payload?.revisionNo||1)]?.status||'WAITING')};if(k==='RAMP')return {...base,status:S(meta?.status||'ĐANG KHAI THÁC'),sessionId:S(meta?.sessionId),assignmentId:S(meta?.assignmentId),workspaceKey:S(meta?.workspaceKey),sourcePath:S(meta?.sourcePath),chockOn:S(meta?.chockOn),doorClose:S(meta?.doorClose),chockOff:S(meta?.chockOff),pushback:S(meta?.pushback),cargoOffload:S(meta?.cargoOffload),cargoOnload:S(meta?.cargoOnload)};return {...base,status:S(meta?.status||'ĐÃ CẬP NHẬT')};}
  root.sagsFlightHubLink=async function(kind,payload,meta={}){try{if(typeof root.sagsV470Ref!=='function')return null;const id=identity(payload,meta),records=await readDate(id.date);let rec=matchRecord(records,id.flights),fid=rec?.flightId;if(!fid){fid=flightId(id.date,id.flights[0],id.flights[1],id.flights.join('/'));rec={flightId:fid,opDate:id.date,flightRaw:id.flights.join('/'),flightName:id.flights.join(' / '),arrFlight:id.flights[0]||'',depFlight:id.flights[1]||'',createdFrom:'MODULE_FALLBACK',createdAtMs:Date.now(),assignments:{}};}const mod=moduleSummary(kind,payload,meta),eventId=`EV_${Date.now()}_${hash(kind+'|'+S(meta.docId)+'|'+Math.random())}`;const patch={};patch[`${ROOT}/${safe(id.date)}/${safe(fid)}/flightId`]=fid;patch[`${ROOT}/${safe(id.date)}/${safe(fid)}/opDate`]=id.date;patch[`${ROOT}/${safe(id.date)}/${safe(fid)}/updatedAtMs`]=Date.now();if(id.reg)patch[`${ROOT}/${safe(id.date)}/${safe(fid)}/acReg`]=id.reg;patch[`${ROOT}/${safe(id.date)}/${safe(fid)}/modules/${safe(mod.kind)}`]=mod;patch[`${ROOT}/${safe(id.date)}/${safe(fid)}/timeline/${safe(eventId)}`]={eventId,kind:mod.kind,status:mod.status,atMs:Date.now(),by:mod.updatedBy,docId:mod.docId,revisionNo:mod.revisionNo};await root.sagsV470Ref('').update(patch);return {flightId:fid,opDate:id.date}}catch(e){console.warn('FlightHub link',kind,e);return null}};
  function rampMeta(){try{const st=root.state||{},meta=typeof root.currentFlightSessionMeta==='function'?root.currentFlightSessionMeta():null,aid=S(meta?.rosterAssignmentId||st.rosterAssignmentId),wi=typeof root.rosterWorkspaceInfo==='function'?root.rosterWorkspaceInfo(aid):null;return {opDate:S(meta?.rosterOpDate),sessionId:S(root.activeFlightSessionId),assignmentId:aid,workspaceKey:S(wi?.workspaceKey),sourcePath:wi?.workspaceKey?`roster_flight_workspaces/${safe(wi.workspaceKey)}`:'',chockOn:S(st.h5||st.f421_h5),doorClose:S(st.h21||st.f421_h21),chockOff:S(st.h22||st.f421_h22),pushback:S(st.h24||st.f421_h24),cargoOffload:S(st.offloadCargoFinish||st.f421_offloadCargoFinish),cargoOnload:S(st.onloadCargoFinish||st.f421_onloadCargoFinish),status:S(st.h24||st.f421_h24)?'PUSHBACK':(S(st.h21||st.f421_h21)?'DOOR CLOSE':'ĐANG KHAI THÁC')}}catch(_){return {}}}
  let syncTimer=0,lastRampSig='';root.sagsFlightHubSyncCurrentRamp=function(){clearTimeout(syncTimer);syncTimer=setTimeout(async()=>{try{if(!root.activeFlightSessionId)return;const st=clone(root.state||{}),m=rampMeta(),sig=JSON.stringify([root.activeFlightSessionId,m.chockOn,m.doorClose,m.chockOff,m.pushback,m.cargoOffload,m.cargoOnload,S(st.fltBefore||st.f421_fltBefore),S(st.fltAfter||st.f421_fltAfter)]);if(sig===lastRampSig)return;lastRampSig=sig;await root.sagsFlightHubLink('RAMP',{state:st},m)}catch(e){console.warn('FlightHub ramp',e)}},700)};
  function installPersistHook(){if(root.__FLIGHT_HUB_PERSIST_HOOK)return;const base=root.persist;if(typeof base!=='function'){setTimeout(installPersistHook,500);return}root.__FLIGHT_HUB_PERSIST_HOOK=1;root.persist=function(){const r=base.apply(this,arguments);try{root.sagsFlightHubSyncCurrentRamp()}catch(_){}return r}}
  function installRefHook(){if(root.__FLIGHT_HUB_REF_HOOK)return;const prev=root.sagsV470Ref;if(typeof prev!=='function'){setTimeout(installRefHook,500);return}root.__FLIGHT_HUB_REF_HOOK=1;root.sagsV470Ref=function(path=''){const ref=prev(path);if(S(path)===''&&ref&&typeof ref.update==='function'){const base=ref.update.bind(ref);ref.update=function(patch){if(patch&&typeof patch==='object'&&!Array.isArray(patch))try{enrichRosterPatch(patch)}catch(e){console.warn('FlightHub roster enrich',e)}return base(patch)}}return ref};}
  root.sagsFlightHubRead=async function(date){return await readDate(isoDate(date))};
  root.sagsFlightHubFlightId=flightId;
  root.__FLIGHT_HUB_HDSD='DAILY ROSTER tạo 1 flightId/hồ sơ mẹ cho mỗi chuyến. FINAL, KẾT SỔ, RAMP/hàng hóa và module liên quan không nhân bản dữ liệu chính thức; mỗi module đăng ký trạng thái + đường dẫn dữ liệu chuẩn vào đúng flightId. Mở chuyến thấy toàn bộ trạng thái trong cùng hồ sơ.';

  function installDailyRosterUi(){
    try{const b=document.getElementById('drPublishBtn');if(b)b.textContent='TẠO CHUYẾN & PHÂN CÔNG';}catch(_){}
    if(root.__FLIGHT_HUB_DAILY_HOOK)return;const base=root.dailyRosterPublish;if(typeof base!=='function'){setTimeout(installDailyRosterUi,500);return}
    root.__FLIGHT_HUB_DAILY_HOOK=1;root.dailyRosterPublish=async function(){const r=await base.apply(this,arguments);try{setTimeout(()=>root.rosterHandoffOpen?.(),250)}catch(_){}return r};
  }
  root.sagsFlightHubModuleBadges=function(rec){const mods=rec?.modules||{},order=['KẾT SỔ','FINAL','RAMP','HÀNG HÓA','ULD','MVT','MVA'];return order.filter(k=>mods[k]).map(k=>({kind:k,status:S(mods[k]?.status||'ĐÃ CÓ'),revisionNo:Number(mods[k]?.revisionNo||0)}));};

  installRefHook();installPersistHook();installDailyRosterUi();root.__FLIGHT_HUB_BUILD=BUILD;
})(typeof window!=='undefined'?window:globalThis);
