/* E-REPORT SAGS V2.3 · DAILY ROSTER flight list + approved handoff workflow.
 * Keeps DAILY ROSTER creation untouched.
 * Flow: current owner A requests B -> AD/department manager approves -> B accepts -> assignment moves A -> B.
 * A stays current owner until B accepts. Every state transition is event-based; no heartbeat.
 */
(function(root){"use strict";
  const MANIFEST_PATH="roster_manifests";
  const MAIL_PATH="roster_mail";
  const SESSION_PATH="roster_sessions";
  const REVOKE_PATH="roster_revocations";
  const HANDOFF_PATH="roster_handoffs";
  const HANDOFF_MAIL_PATH="roster_handoff_mail";
  const MANAGER_TITLES=new Set(["TRƯỞNG PHÒNG","PHÓ PHÒNG","ĐỘI TRƯỞNG","ĐỘI PHÓ","CA TRƯỞNG","CA PHÓ"]);
  const S=x=>String(x??"").trim();
  const U=x=>S(x).toUpperCase();
  const esc=x=>S(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const safe=x=>S(x).replace(/[.#$\[\]\/]/g,"_");
  const norm=x=>{try{return typeof normalizePersonalUsername==="function"?normalizePersonalUsername(x):U(x)}catch(_){return U(x)}};
  const now=()=>Date.now();
  function profile(){try{return typeof currentUserProfile!=="undefined"?currentUserProfile:(root.currentUserProfile||null)}catch(_){return root.currentUserProfile||null}}
  function currentRoleValue(){try{return typeof currentRole!=="undefined"?currentRole:(root.currentRole||"")}catch(_){return root.currentRole||""}}
  function me(){const p=profile();return norm(p?.username||(U(currentRoleValue())==="AD"?"AD":""));}
  function actor(){try{return typeof currentActor==="function"?currentActor():{username:me(),name:S(profile()?.name||me()),role:U(currentRoleValue())}}catch(_){return {username:me(),name:S(profile()?.name||me()),role:U(currentRoleValue())}}}
  function role(){return U(currentRoleValue()||profile()?.role)}
  function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
  function fmt(ms){if(!ms)return "";try{return new Date(Number(ms)).toLocaleString("vi-VN",{hour:"2-digit",minute:"2-digit",day:"2-digit",month:"2-digit"})}catch(_){return ""}}
  function formLabel(g){return g==="fsags421"?"42.1":g==="fsags551"?"55.1":g==="fsags09"?"FSAGS 09":"42.3";}
  function dbref(path){if(typeof sagsV470Ref!=="function")throw new Error("RTDB chưa sẵn sàng.");return sagsV470Ref(path);}
  async function catalog(force=false){try{return typeof v466GetUserCatalog==="function"?await v466GetUserCatalog(force):[]}catch(_){return []}}
  function profileOf(items,username){const u=norm(username);return (items||[]).find(x=>norm(x.username)===u)||null;}
  function depOf(p){return U(p?.departmentCode||p?.systemDepartment||"");}
  function groupOf(p){return U(p?.groupCode||"");}
  function isManagerProfile(p){return !!p&&p.active!==false&&MANAGER_TITLES.has(U(p.jobTitle));}
  function sameOperationalUnit(a,b){if(!a||!b)return false;if(U(a.role)!==U(b.role))return false;const ad=depOf(a),bd=depOf(b);if(ad&&bd&&ad!==bd)return false;const ag=groupOf(a),bg=groupOf(b);return !(ag&&bg&&ag!==bg);}
  function canApproveFor(h,items){if(role()==="AD")return true;const p=profileOf(items,me());if(!isManagerProfile(p))return false;const dep=U(h.departmentCode||"");return !!dep&&depOf(p)===dep;}
  async function readManifest(date){const s=await dbref(`${MANIFEST_PATH}/${safe(date)}`).once("value");return s.val()||null;}
  async function readHandoffs(date){const s=await dbref(`${HANDOFF_PATH}/${safe(date)}`).once("value");return s.val()||{};}
  function assignmentIdOf(h){return S(h.assignmentId);}
  function handoffId(assignmentId){return `RH_${safe(assignmentId)}_${now()}_${Math.random().toString(36).slice(2,7).toUpperCase()}`;}
  async function mailPayload(user,id,item,date){let p=null;try{p=(await dbref(`${MAIL_PATH}/${safe(user)}/items/${safe(id)}`).once("value")).val();}catch(_){ }
    return p||{engine:"daily-roster-v2",schema:2,assignmentId:id,opDate:date,flightRaw:S(item.flightRaw),flightName:S(item.flightName),formGroup:S(item.formGroup||"fsags"),sourceColumn:S(item.sourceColumn),roleKey:S(item.roleKey),workspaceKey:S(item.workspaceKey||item.rosterWorkspaceKey),rosterWorkspaceKey:S(item.workspaceKey||item.rosterWorkspaceKey),assignmentScope:S(item.assignmentScope||"BOTH"),active:true};
  }
  function ensureUI(){
    if(document.getElementById("rhModal"))return;
    const st=document.createElement("style");st.textContent=`
      #rhModal{display:none;position:fixed;inset:0;z-index:16540;background:rgba(0,0,0,.52);align-items:center;justify-content:center;padding:10px;font-family:Arial,sans-serif}#rhModal.show{display:flex}
      .rhPanel{width:min(98vw,1080px);max-height:94vh;overflow:auto;background:#fff;border-radius:16px;padding:14px;box-sizing:border-box;box-shadow:0 18px 50px rgba(0,0,0,.3)}.rhHead{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.rhHead h3{margin:0;color:#0b4f91}.rhSub{font-size:12px;color:#5d6875;line-height:1.45;margin:5px 0 10px}.rhTools{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.rhTools input{padding:8px;border:1px solid #cad6df;border-radius:8px}.rhBtn{border:0;border-radius:9px;padding:8px 11px;font-weight:800;background:#0b67b2;color:#fff;cursor:pointer}.rhBtn.gray{background:#eef3f7;color:#31475a;border:1px solid #ccd7df}.rhBtn.green{background:#15803d}.rhBtn.orange{background:#b45309}.rhBtn.red{background:#b42318}.rhBtn:disabled{opacity:.45;cursor:not-allowed}
      .rhTabs{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.rhTab{border:1px solid #c9d6e1;background:#f6f9fc;color:#27465f;border-radius:999px;padding:7px 11px;font-weight:800;cursor:pointer}.rhTab.on{background:#0b67b2;color:#fff;border-color:#0b67b2}.rhBadge{display:inline-block;min-width:18px;text-align:center;border-radius:999px;background:#b42318;color:#fff;padding:1px 6px;font-size:11px;margin-left:4px}
      .rhFlight{border:1px solid #d7e1e9;border-radius:12px;margin:8px 0;overflow:hidden}.rhFlightHead{padding:9px 10px;background:#edf5fb;display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}.rhFlightHead b{color:#173f60}.rhAssign{padding:9px 10px;border-top:1px solid #e6edf2;display:grid;grid-template-columns:minmax(160px,1.3fr) minmax(150px,1fr) minmax(170px,1.4fr);gap:8px;align-items:center;font-size:12px}.rhMeta{color:#607080}.rhOwner{font-weight:800;color:#164d73}.rhActions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.rhEmpty{padding:16px;text-align:center;color:#657482}.rhStatus{margin:8px 0;padding:8px 10px;border-radius:9px;background:#eef6ff;color:#244862;font-size:12px;white-space:pre-wrap}.rhStatus.err{background:#fff0f0;color:#9b1c1c}.rhCard{border:1px solid #d8e2ea;border-radius:11px;padding:10px;margin:8px 0}.rhCard.pending{border-color:#e0b46a;background:#fffaf0}.rhCard.approved{border-color:#79b98d;background:#f4fbf6}.rhCard.done{border-color:#86a9c6;background:#f5f9fc}.rhCard .title{font-weight:900;color:#173f60}.rhCard .line{font-size:12px;color:#596b79;margin-top:4px}.rhCard .buttons{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}
      #rhNotice{display:none;position:fixed;left:50%;top:max(12px,env(safe-area-inset-top));transform:translateX(-50%);z-index:17550;width:min(92vw,560px);background:#123d64;color:#fff;border-radius:13px;padding:11px 12px;box-shadow:0 10px 32px rgba(0,0,0,.3);font:13px Arial;box-sizing:border-box}#rhNotice.show{display:block}#rhNotice b{display:block;margin-bottom:4px}#rhNotice button{margin-top:7px;border:0;border-radius:8px;padding:7px 10px;font-weight:800;cursor:pointer}
      @media(max-width:720px){.rhAssign{grid-template-columns:1fr}.rhActions{justify-content:flex-start}.rhPanel{padding:10px}.rhBtn{padding:9px 10px}}
    `;document.head.appendChild(st);
    const m=document.createElement("div");m.id="rhModal";m.innerHTML=`<div class="rhPanel"><div class="rhHead"><div><h3>✈ DANH SÁCH CHUYẾN · DAILY ROSTER</h3><div class="rhSub">Mỗi chuyến dùng workspace chung. Bàn giao chỉ có hiệu lực sau khi AD/Quản lý bộ phận duyệt và người nhận xác nhận tiếp nhận.</div></div><button class="rhBtn gray" onclick="rosterHandoffClose()">ĐÓNG</button></div><div class="rhTools"><input id="rhDate" type="date"><button class="rhBtn" onclick="rosterHandoffRefresh()">TẢI DANH SÁCH</button></div><div class="rhTabs"><button id="rhTabFlights" class="rhTab on" onclick="rosterHandoffTab('flights')">CHUYẾN BAY</button><button id="rhTabMine" class="rhTab" onclick="rosterHandoffTab('mine')">BÀN GIAO CỦA TÔI <span id="rhMineBadge"></span></button><button id="rhTabApprove" class="rhTab" onclick="rosterHandoffTab('approve')">CHỜ DUYỆT <span id="rhApproveBadge"></span></button></div><div id="rhStatus" class="rhStatus">Đang tải…</div><div id="rhBody"></div></div>`;document.body.appendChild(m);document.getElementById("rhDate").value=today();
    const n=document.createElement("div");n.id="rhNotice";n.innerHTML=`<b id="rhNoticeTitle"></b><div id="rhNoticeText"></div><button onclick="rosterHandoffOpenFromNotice()">MỞ DANH SÁCH CHUYẾN</button> <button onclick="rosterHandoffDismissNotice()">ĐÓNG</button>`;document.body.appendChild(n);
  }
  function ensureButton(){const bar=document.querySelector(".toolbar-row.main-actions");if(!bar)return;let b=document.getElementById("roleBtnRosterFlights");if(!b){b=document.createElement("button");b.id="roleBtnRosterFlights";b.textContent="✈ CHUYẾN HÔM NAY";b.onclick=()=>root.rosterHandoffOpen?.();const a=document.getElementById("roleBtnFlights");if(a?.parentNode)a.parentNode.insertBefore(b,a.nextSibling);else bar.appendChild(b);}b.style.display=role()?"":"none";}
  let currentTab="flights",cache={manifest:null,handoffs:{},users:[],flights:{}},mailRef=null,mailCb=null,noticeQueue=[],noticeShowing=false;
  function status(t,err=false){const e=document.getElementById("rhStatus");if(e){e.textContent=t;e.classList.toggle("err",!!err)}}
  function selectedDate(){return S(document.getElementById("rhDate")?.value)||today();}
  function pendingForMe(h){const u=me();return h&&(norm(h.fromUser)===u||norm(h.toUser)===u);}
  function actionBadge(){const hs=Object.values(cache.handoffs||{}),u=me();const mine=hs.filter(h=>pendingForMe(h)&&!["COMPLETED","REJECTED","CANCELLED"].includes(U(h.status))).length;const appr=hs.filter(h=>U(h.status)==="PENDING_APPROVAL"&&canApproveFor(h,cache.users)).length;document.getElementById("rhMineBadge").innerHTML=mine?`<span class="rhBadge">${mine}</span>`:"";document.getElementById("rhApproveBadge").innerHTML=appr?`<span class="rhBadge">${appr}</span>`:"";}
  function groupedAssignments(){const items=Object.values(cache.manifest?.items||{}).filter(x=>x&&x.active!==false);const m=new Map();for(const a of items){const k=S(a.flightRaw||a.flightName||a.assignmentId);if(!m.has(k))m.set(k,[]);m.get(k).push(a);}return [...m.entries()].sort((a,b)=>S(a[0]).localeCompare(S(b[0])));}
  function latestHandoffForAssignment(id){return Object.values(cache.handoffs||{}).filter(h=>assignmentIdOf(h)===S(id)&&!["COMPLETED","REJECTED","CANCELLED"].includes(U(h.status))).sort((a,b)=>Number(b.updatedAtMs||b.requestedAtMs||0)-Number(a.updatedAtMs||a.requestedAtMs||0))[0]||null;}
    function renderFlights(){const host=document.getElementById("rhBody"),u=me(),groups=groupedAssignments();if(!groups.length){host.innerHTML='<div class="rhEmpty">Ngày này chưa có chuyến được tạo từ DAILY ROSTER.</div>';return;}const hubs=Object.values(cache.flights||{});host.innerHTML=groups.map(([flight,arr])=>{const a0=arr[0]||{},fid=S(a0.flightId),hub=hubs.find(x=>S(x.flightId)===fid)||hubs.find(x=>S(x.flightRaw)===S(flight))||null,badges=(typeof sagsFlightHubModuleBadges==="function"?sagsFlightHubModuleBadges(hub):[]),moduleLine=badges.length?`<div class="rhMeta" style="width:100%;margin-top:5px">${badges.map(x=>`<span style="display:inline-block;margin:2px 4px 0 0;padding:3px 7px;border-radius:999px;background:#e9f7ee;color:#17643a;font-weight:900">${esc(x.kind)}: ${esc(x.status)}${x.revisionNo?` · L${x.revisionNo}`:""}</span>`).join("")}</div>`:`<div class="rhMeta" style="width:100%;margin-top:5px">Hồ sơ chuyến đã tạo · chưa có dữ liệu nghiệp vụ phát sinh.</div>`;return `<div class="rhFlight"><div class="rhFlightHead"><div><b>${esc(flight)}</b>${fid?`<div class="rhMeta">${esc(fid)}</div>`:""}</div><span class="rhMeta">STA ${esc(a0.sta||hub?.sta||"—")} · STD ${esc(a0.std||hub?.std||"—")} · ${esc(a0.acReg||hub?.acReg||"")}</span>${moduleLine}</div>${arr.map(a=>{const owner=norm(a.user||a.targetUser),h=latestHandoffForAssignment(a.assignmentId),isMine=owner===u,local=(typeof readFlightSessionList==="function"?readFlightSessionList():[]).find(x=>S(x.rosterAssignmentId)===S(a.assignmentId));let hs="";if(h)hs=`<div class="rhMeta">Bàn giao: ${esc(h.fromUser)} → ${esc(h.toUser)} · <b>${esc(statusLabel(h.status))}</b></div>`;return `<div class="rhAssign"><div><b>${esc(formLabel(a.formGroup))}</b> · ${esc(a.sourceColumn||a.roleKey||"")}<div class="rhMeta">${esc(a.assignmentScope||"BOTH")}</div></div><div><span class="rhOwner">${esc(owner||"CHƯA CÓ")}</span>${hs}</div><div class="rhActions">${isMine&&local?`<button class="rhBtn green" onclick="rosterHandoffOpenWork('${esc(a.assignmentId)}')">MỞ CÔNG VIỆC</button>`:""}${isMine&&!h?`<button class="rhBtn orange" onclick="rosterHandoffRequest('${esc(a.assignmentId)}')">BÀN GIAO</button>`:""}${isMine&&h&&U(h.status)==="PENDING_APPROVAL"?`<button class="rhBtn red" onclick="rosterHandoffCancel('${esc(h.id)}')">HỦY YÊU CẦU</button>`:""}</div></div>`}).join("")}</div>`}).join("");}
  function statusLabel(s){s=U(s);return s==="PENDING_APPROVAL"?"CHỜ DUYỆT":s==="APPROVED_WAITING_ACCEPT"?"ĐÃ DUYỆT · CHỜ TIẾP NHẬN":s==="COMPLETED"?"ĐÃ BÀN GIAO":s==="REJECTED"?"ĐÃ TỪ CHỐI":s==="CANCELLED"?"ĐÃ HỦY":s;}
  function handoffCard(h,mode){const canAp=canApproveFor(h,cache.users),isTo=norm(h.toUser)===me(),isFrom=norm(h.fromUser)===me();return `<div class="rhCard ${U(h.status)==="PENDING_APPROVAL"?"pending":U(h.status)==="APPROVED_WAITING_ACCEPT"?"approved":"done"}"><div class="title">${esc(h.flightRaw||h.flightName)} · ${esc(formLabel(h.formGroup))}</div><div class="line"><b>${esc(h.fromUser)}</b> → <b>${esc(h.toUser)}</b> · ${esc(statusLabel(h.status))}</div><div class="line">Đề nghị: ${esc(fmt(h.requestedAtMs))}${h.approvedAtMs?` · Duyệt: ${esc(h.approvedByName||h.approvedBy)} ${esc(fmt(h.approvedAtMs))}`:""}${h.acceptedAtMs?` · Tiếp nhận: ${esc(fmt(h.acceptedAtMs))}`:""}</div>${h.reason?`<div class="line">Lý do: ${esc(h.reason)}</div>`:""}<div class="buttons">${mode==="approve"&&canAp&&U(h.status)==="PENDING_APPROVAL"?`<button class="rhBtn green" onclick="rosterHandoffApprove('${esc(h.id)}')">DUYỆT</button><button class="rhBtn red" onclick="rosterHandoffReject('${esc(h.id)}')">TỪ CHỐI</button>`:""}${isTo&&U(h.status)==="APPROVED_WAITING_ACCEPT"?`<button class="rhBtn green" onclick="rosterHandoffAccept('${esc(h.id)}')">TIẾP NHẬN</button>`:""}${isFrom&&U(h.status)==="PENDING_APPROVAL"?`<button class="rhBtn red" onclick="rosterHandoffCancel('${esc(h.id)}')">HỦY YÊU CẦU</button>`:""}</div></div>`;}
  function renderMine(){const host=document.getElementById("rhBody"),hs=Object.values(cache.handoffs||{}).filter(pendingForMe).sort((a,b)=>Number(b.updatedAtMs||0)-Number(a.updatedAtMs||0));host.innerHTML=hs.length?hs.map(h=>handoffCard(h,"mine")).join(""):'<div class="rhEmpty">Không có yêu cầu bàn giao liên quan tài khoản này.</div>';}
  function renderApprove(){const host=document.getElementById("rhBody"),hs=Object.values(cache.handoffs||{}).filter(h=>U(h.status)==="PENDING_APPROVAL"&&canApproveFor(h,cache.users)).sort((a,b)=>Number(a.requestedAtMs||0)-Number(b.requestedAtMs||0));host.innerHTML=hs.length?hs.map(h=>handoffCard(h,"approve")).join(""):'<div class="rhEmpty">Không có yêu cầu nào đang chờ bạn duyệt.</div>';}
  function render(){actionBadge();document.querySelectorAll(".rhTab").forEach(x=>x.classList.remove("on"));document.getElementById(currentTab==="flights"?"rhTabFlights":currentTab==="mine"?"rhTabMine":"rhTabApprove")?.classList.add("on");if(currentTab==="flights")renderFlights();else if(currentTab==="mine")renderMine();else renderApprove();}
  root.rosterHandoffTab=function(t){currentTab=t;render();};
  root.rosterHandoffRefresh=async function(){ensureUI();const d=selectedDate();status("Đang tải chuyến, hồ sơ nghiệp vụ và trạng thái bàn giao…");try{const [man,hs,users,flights]=await Promise.all([readManifest(d),readHandoffs(d),catalog(false),typeof sagsFlightHubRead==="function"?sagsFlightHubRead(d):Promise.resolve({})]);cache={manifest:man,handoffs:hs,users,flights:flights||{}};status(man?`Ngày ${d}: ${Object.keys(cache.flights||{}).length} chuyến · ${Object.keys(man.items||{}).length} phân công · ${Object.keys(hs||{}).length} lịch sử/yêu cầu bàn giao.`:`Ngày ${d} chưa có DAILY ROSTER.`);render();}catch(e){status("Không tải được danh sách: "+S(e?.message||e),true)}};
  root.rosterHandoffOpen=function(){ensureUI();document.getElementById("rhModal")?.classList.add("show");document.getElementById("rhDate").value=today();currentTab="flights";void root.rosterHandoffRefresh();};
  root.rosterHandoffClose=function(){document.getElementById("rhModal")?.classList.remove("show");};
  root.rosterHandoffOpenWork=function(id){try{const list=typeof readFlightSessionList==="function"?readFlightSessionList():[],x=list.find(v=>S(v.rosterAssignmentId)===S(id));if(!x)return alert("Công việc chưa được đồng bộ về máy này. Hãy mở lại danh sách sau vài giây.");if(typeof switchFlightSession==="function")switchFlightSession(x.id);root.rosterHandoffClose();}catch(e){alert("Không mở được công việc: "+S(e?.message||e))}};
  root.rosterHandoffRequest=async function(id){try{const d=selectedDate(),man=cache.manifest||await readManifest(d),item=man?.items?.[id];if(!item)throw new Error("Không tìm thấy phân công.");const from=norm(item.user||item.targetUser);if(from!==me())throw new Error("Chỉ người đang phụ trách mới được đề nghị bàn giao.");if(latestHandoffForAssignment(id))throw new Error("Phân công này đã có yêu cầu bàn giao đang xử lý.");const users=cache.users?.length?cache.users:await catalog(false),fromP=profileOf(users,from);if(!fromP)throw new Error("Không tìm thấy hồ sơ tài khoản hiện tại trong catalog.");const candidates=users.filter(x=>x.active!==false&&norm(x.username)!==from&&sameOperationalUnit(fromP,x)).sort((a,b)=>S(a.name).localeCompare(S(b.name),"vi"));if(!candidates.length)throw new Error("Không có tài khoản cùng bộ phận/vai trò để bàn giao.");const text=candidates.map((x,i)=>`${i+1}. ${x.name} (${x.username})`).join("\n");const pick=prompt(`BÀN GIAO ${item.flightRaw||""} · ${formLabel(item.formGroup)}\n\nChọn số người tiếp nhận:\n${text}`);if(pick===null)return;const idx=Number(pick)-1,toP=candidates[idx];if(!toP)throw new Error("Lựa chọn người nhận không hợp lệ.");const reason=prompt("Lý do/ghi chú bàn giao (có thể để trống):","");if(reason===null)return;const hid=handoffId(id),t=now(),h={id:hid,opDate:d,assignmentId:id,workspaceKey:S(item.workspaceKey||item.rosterWorkspaceKey),assignmentScope:S(item.assignmentScope||"BOTH"),flightRaw:S(item.flightRaw),flightName:S(item.flightName),formGroup:S(item.formGroup),sourceColumn:S(item.sourceColumn),roleKey:S(item.roleKey),fromUser:from,fromName:S(fromP.name||from),toUser:norm(toP.username),toName:S(toP.name||toP.username),departmentCode:depOf(fromP),groupCode:groupOf(fromP),role:U(fromP.role),reason:S(reason),status:"PENDING_APPROVAL",requestedAtMs:t,updatedAtMs:t,requestedBy:actor()};const patch={};patch[`${HANDOFF_PATH}/${safe(d)}/${safe(hid)}`]=h;patch[`${HANDOFF_MAIL_PATH}/${safe(from)}/${safe(hid)}`]={id:hid,opDate:d,status:h.status,updatedAtMs:t};
      const approvers=users.filter(x=>(U(x.role)==="AD")||(isManagerProfile(x)&&depOf(x)===depOf(fromP)));for(const p of approvers)patch[`${HANDOFF_MAIL_PATH}/${safe(norm(p.username))}/${safe(hid)}`]={id:hid,opDate:d,status:h.status,updatedAtMs:t,kind:"APPROVAL"};patch[`${HANDOFF_MAIL_PATH}/AD/${safe(hid)}`]={id:hid,opDate:d,status:h.status,updatedAtMs:t,kind:"APPROVAL"};await dbref("").update(patch);status(`✓ Đã gửi đề nghị ${from} → ${h.toUser}. A vẫn là người phụ trách cho đến khi được duyệt và B bấm TIẾP NHẬN.`);await root.rosterHandoffRefresh();}catch(e){status("Không tạo được bàn giao: "+S(e?.message||e),true)}};
  async function getHandoff(id){const d=selectedDate(),snap=await dbref(`${HANDOFF_PATH}/${safe(d)}/${safe(id)}`).once("value");return {d,h:snap.val()||null};}
  root.rosterHandoffApprove=async function(id){try{const {d,h}=await getHandoff(id);if(!h||U(h.status)!=="PENDING_APPROVAL")throw new Error("Yêu cầu không còn ở trạng thái chờ duyệt.");const users=cache.users?.length?cache.users:await catalog(false);if(!canApproveFor(h,users))throw new Error("Bạn không có quyền duyệt yêu cầu của bộ phận này.");const a=actor(),t=now(),patch={};patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/status`]="APPROVED_WAITING_ACCEPT";patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/approvedAtMs`]=t;patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/approvedBy`]=norm(a.username||me());patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/approvedByName`]=S(a.name||a.username);patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/updatedAtMs`]=t;patch[`${HANDOFF_MAIL_PATH}/${safe(h.toUser)}/${safe(id)}`]={id,opDate:d,status:"APPROVED_WAITING_ACCEPT",updatedAtMs:t,kind:"ACCEPT"};patch[`${HANDOFF_MAIL_PATH}/${safe(h.fromUser)}/${safe(id)}`]={id,opDate:d,status:"APPROVED_WAITING_ACCEPT",updatedAtMs:t};await dbref("").update(patch);status(`✓ Đã duyệt. ${h.toUser} đã nhận thông báo và phải bấm TIẾP NHẬN trước khi quyền được chuyển.`);await root.rosterHandoffRefresh();}catch(e){status("Không duyệt được: "+S(e?.message||e),true)}};
  root.rosterHandoffReject=async function(id){try{const {d,h}=await getHandoff(id);if(!h||U(h.status)!=="PENDING_APPROVAL")throw new Error("Yêu cầu không còn ở trạng thái chờ duyệt.");const users=cache.users?.length?cache.users:await catalog(false);if(!canApproveFor(h,users))throw new Error("Bạn không có quyền từ chối yêu cầu này.");const note=prompt("Lý do từ chối (có thể để trống):","");if(note===null)return;const a=actor(),t=now(),patch={};patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/status`]="REJECTED";patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/rejectedAtMs`]=t;patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/rejectedBy`]=norm(a.username||me());patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/rejectedByName`]=S(a.name||a.username);patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/rejectReason`]=S(note);patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/updatedAtMs`]=t;patch[`${HANDOFF_MAIL_PATH}/${safe(h.fromUser)}/${safe(id)}`]={id,opDate:d,status:"REJECTED",updatedAtMs:t};await dbref("").update(patch);status("Đã từ chối yêu cầu bàn giao.");await root.rosterHandoffRefresh();}catch(e){status("Không từ chối được: "+S(e?.message||e),true)}};
  root.rosterHandoffCancel=async function(id){try{const {d,h}=await getHandoff(id);if(!h||norm(h.fromUser)!==me()||U(h.status)!=="PENDING_APPROVAL")throw new Error("Chỉ người đề nghị được hủy khi yêu cầu còn chờ duyệt.");if(!confirm("Hủy yêu cầu bàn giao này?"))return;const t=now();await dbref("").update({[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/status`]:"CANCELLED",[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/cancelledAtMs`]:t,[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/updatedAtMs`]:t});status("Đã hủy yêu cầu bàn giao.");await root.rosterHandoffRefresh();}catch(e){status("Không hủy được: "+S(e?.message||e),true)}};
  root.rosterHandoffAccept=async function(id){try{const {d,h}=await getHandoff(id);if(!h||U(h.status)!=="APPROVED_WAITING_ACCEPT")throw new Error("Yêu cầu chưa được duyệt hoặc đã xử lý.");if(norm(h.toUser)!==me())throw new Error("Chỉ đúng người được bàn giao mới được tiếp nhận.");const man=await readManifest(d),item=man?.items?.[h.assignmentId];if(!item)throw new Error("Không còn tìm thấy assignment trong DAILY ROSTER.");const current=norm(item.user||item.targetUser);if(current!==norm(h.fromUser))throw new Error(`Người phụ trách đã thay đổi (${current}); không thể áp dụng yêu cầu cũ.`);if(!confirm(`TIẾP NHẬN ${h.flightRaw||""} · ${formLabel(h.formGroup)} từ ${h.fromUser}?\n\nSau xác nhận, bạn trở thành người phụ trách hiện tại.`))return;const t=now(),old=norm(h.fromUser),target=norm(h.toUser),payload=await mailPayload(old,h.assignmentId,item,d);const a=actor();const nextPayload={...payload,targetUser:target,originalTargetUser:item.originalUser||payload.originalTargetUser||old,manualOverride:true,reassignedFrom:old,reassignedAtMs:t,reassignedBy:target,handoffId:id,handoffApprovedBy:S(h.approvedBy),active:true};const nextItem={...item,user:target,originalUser:item.originalUser||payload.originalTargetUser||old,manualOverride:true,assignmentId:h.assignmentId,lastHandoffId:id,lastHandoffAtMs:t};const patch={};patch[`${MAIL_PATH}/${safe(old)}/items/${safe(h.assignmentId)}`]=null;patch[`${MAIL_PATH}/${safe(target)}/items/${safe(h.assignmentId)}`]=nextPayload;patch[`${REVOKE_PATH}/${safe(old)}/items/${safe(h.assignmentId)}`]={assignmentId:h.assignmentId,reason:"APPROVED_HANDOFF",toUser:target,atMs:t,by:target,handoffId:id};patch[`${REVOKE_PATH}/${safe(target)}/items/${safe(h.assignmentId)}`]=null;patch[`${MANIFEST_PATH}/${safe(d)}/items/${safe(h.assignmentId)}`]=nextItem;patch[`${SESSION_PATH}/${safe(h.assignmentId)}/ownerUser`]=target;patch[`${SESSION_PATH}/${safe(h.assignmentId)}/reassignedAtMs`]=t;patch[`${SESSION_PATH}/${safe(h.assignmentId)}/reassignedBy`]=target;patch[`${SESSION_PATH}/${safe(h.assignmentId)}/handoffId`]=id;patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/status`]="COMPLETED";patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/acceptedAtMs`]=t;patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/acceptedBy`]=target;patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/acceptedByName`]=S(a.name||target);patch[`${HANDOFF_PATH}/${safe(d)}/${safe(id)}/updatedAtMs`]=t;patch[`${HANDOFF_MAIL_PATH}/${safe(old)}/${safe(id)}`]={id,opDate:d,status:"COMPLETED",updatedAtMs:t};patch[`${HANDOFF_MAIL_PATH}/${safe(target)}/${safe(id)}`]={id,opDate:d,status:"COMPLETED",updatedAtMs:t};await dbref("").update(patch);status(`✓ ${target} đã tiếp nhận. Người phụ trách hiện tại: ${target}. Lịch sử ${old} → ${target} được giữ trong hồ sơ bàn giao.`);await root.rosterHandoffRefresh();}catch(e){status("Không tiếp nhận được: "+S(e?.message||e),true)}};
  function seenKey(id,status){return `sags_rh_seen_${safe(me())}_${safe(id)}_${safe(status)}`}
  function enqueueNotice(x){if(!x?.id||!x.status)return;const k=seenKey(x.id,x.status);try{if(localStorage.getItem(k))return;localStorage.setItem(k,"1")}catch(_){ }noticeQueue.push(x);showNextNotice();}
  async function showNextNotice(){if(noticeShowing||!noticeQueue.length)return;noticeShowing=true;const x=noticeQueue.shift();let title="THÔNG BÁO BÀN GIAO",text=statusLabel(x.status);try{const snap=await dbref(`${HANDOFF_PATH}/${safe(x.opDate||today())}/${safe(x.id)}`).once("value"),h=snap.val()||{};if(U(x.status)==="PENDING_APPROVAL"&&role()==="AD"){title="CÓ YÊU CẦU BÀN GIAO CHỜ DUYỆT";text=`${h.flightRaw||""} · ${h.fromUser||""} → ${h.toUser||""}`;}else if(U(x.status)==="APPROVED_WAITING_ACCEPT"&&norm(h.toUser)===me()){title="CHUYẾN ĐƯỢC BÀN GIAO CHO BẠN";text=`${h.flightRaw||""} · ${formLabel(h.formGroup)} · từ ${h.fromUser||""}. Mở danh sách để TIẾP NHẬN.`;}else if(U(x.status)==="REJECTED"){title="YÊU CẦU BÀN GIAO BỊ TỪ CHỐI";text=`${h.flightRaw||""} · ${h.fromUser||""} → ${h.toUser||""}`;}else if(U(x.status)==="COMPLETED"){title="BÀN GIAO ĐÃ HOÀN TẤT";text=`${h.flightRaw||""} · ${h.fromUser||""} → ${h.toUser||""}`;}}catch(_){ }
    const n=document.getElementById("rhNotice");document.getElementById("rhNoticeTitle").textContent=title;document.getElementById("rhNoticeText").textContent=text;n?.classList.add("show");}
  root.rosterHandoffDismissNotice=function(){document.getElementById("rhNotice")?.classList.remove("show");noticeShowing=false;setTimeout(showNextNotice,120);};
  root.rosterHandoffOpenFromNotice=function(){root.rosterHandoffDismissNotice();root.rosterHandoffOpen();currentTab="mine";setTimeout(()=>{currentTab="mine";render()},300);};
  function stopMail(){try{if(mailRef&&mailCb)mailRef.off("child_added",mailCb);}catch(_){ }mailRef=mailCb=null;}
  function startMail(){stopMail();const u=me();if(!u)return;try{mailRef=dbref(`${HANDOFF_MAIL_PATH}/${safe(u)}`);mailCb=s=>enqueueNotice(s.val()||{});mailRef.on("child_added",mailCb,e=>console.warn("handoff mail",e));}catch(e){console.warn("handoff listener",e)}}
  const baseApply=root.applyRoleUI;if(typeof baseApply==="function")root.applyRoleUI=function(){const r=baseApply.apply(this,arguments);setTimeout(()=>{ensureUI();ensureButton();startMail()},0);return r;};
  setTimeout(()=>{ensureUI();ensureButton();startMail()},1000);
  root.__ROSTER_HANDOFF_HDSD="DAILY ROSTER tạo danh sách chuyến. Người đang phụ trách A bấm BÀN GIAO và chọn B cùng bộ phận/vai trò. A vẫn phụ trách trong lúc chờ. AD hoặc quản lý cùng phòng (Trưởng/Phó phòng, Đội trưởng/Đội phó, Ca trưởng/Ca phó) DUYỆT. Sau duyệt B nhận thông báo và bấm TIẾP NHẬN. Chỉ lúc đó assignment/workspace mới chuyển A→B; lịch sử người đề nghị, người duyệt, người tiếp nhận và thời gian được giữ trong roster_handoffs.";
})(typeof window!=="undefined"?window:globalThis);
